return {
    { "folke/tokyonight.nvim", enabled = false },
    { "nvim-java/nvim-java", enabled = false },
    { "akinsho/bufferline.nvim", enabled = false },
    { "folke/todo-comments.nvim", enabled = false },
    { "folke/persistence.nvim", enabled = false },
    { "folke/ts-comments.nvim", enabled = false },
    { "nvim-lualine/lualine.nvim", enabled = false },
    { "mfussenegger/nvim-dap.nvim", enabled = false },
    { "rcarriga/nvim-dap-ui.nvim", enabled = false },
    { "jay-babu/mason-nvim-dap.nvim", enabled = false },
    { "theHamsta/nvim-dap-virtual-text", enabled = false },
    { "MagicDuck/grug-far.nvim", enabled = false },
    { "folke/flash.nvim", enabled = false },
    { "windwp/nvim-ts-autotag", enabled = false },
}
