CompileFlags:
  Add: 
    - "-std=c11"
    - "-Wall"
    - "-Wextra"
    - "-pedantic"
  Remove: 
    - "-W*"  # Remove warnings conflitantes
    - "-std=c++*"  # Remove padrões C++

Index:
  Background: Build
  StandardLibrary: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes

Completion:
  AllScopes: No  # Não sugerir símbolos de outros escopos desnecessariamente

Diagnostics:
  ClangTidy:
    Add: 
      - "readability-*"
      - "bugprone-*"
      - "performance-*"
      - "portability-*"
    Remove:
      - "readability-braces-around-statements"  # Muito rígido para C
      - "bugprone-easily-swappable-parameters"
  UnusedIncludes: Strict
  MissingIncludes: Strict
